name: Build and Publish

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  TARGET: x86_64-pc-windows-msvc

permissions:
  contents: write
  actions: read

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Build Script
      run: .\build.ps1
      shell: pwsh

    - name: Calculate SHA-256 Checksum
      run: |
        $BUILD_DIR = "target\${{ env.TARGET }}\release"
        # This is a more robust way to get just the hash value from certutil
        $kbscroll_sha = (certutil -hashfile "$BUILD_DIR\kbscroll.exe" SHA256)[1].Trim()
        $kbscroll_sha | Out-File -FilePath kbscroll_sha256.txt
      shell: pwsh

    - name: Get Release Version
      id: get_version
      run: |
        $VERSION = (Select-String '^version =' Cargo.toml).Line.Split('"')[1]
        echo "RELEASE_NAME=Release $VERSION" >> $env:GITHUB_OUTPUT
      shell: pwsh
      
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ steps.get_version.outputs.RELEASE_NAME }}
        draft: false
        prerelease: false
        generate_release_notes: true
        body: ≽^•⩊•^≼
        files: |
          target/${{ env.TARGET }}/release/kbscroll.exe
          kbscroll_sha256.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}