name: Build and Publish

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write  # Required to create releases
  actions: read    # Required to use actions

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Release
      run: cargo build --release --verbose

    - name: Compress with UPX
      run: |
        choco install upx  # Install UPX using Chocolatey
        upx --best --lzma target/release/kbscroll.exe -o target/release/kbscroll_tiny.exe  # Compress the executable and rename it

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/release/kbscroll.exe
        asset_name: kbscroll.exe
        asset_content_type: application/octet-stream

    - name: Upload UPX Compressed Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/release/kbscroll_tiny.exe
        asset_name: kbscroll_tiny.exe
        asset_content_type: application/octet-stream
